spring:
    profiles: dev
    application:
        name: microservicecloud-config-atguigu-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/

server:
  port:8201