spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  cloud:
    config:
      enabled: false
server:
  port: 8201

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8201
    prefer-ip-address: true
    #status-page-url: http://192.168.88.189:8001/info

#配置DeptProvider8001 info信息 动态获取artifactId和version 用 ${}
info:
  app.name: taosun-microservicecloud
  company.name: 江苏曜晨科技有限公司
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
  
---
spring:
  profiles: test
  cloud:
    config:
      enabled: false
    

server:
  port: 8202

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8202
    prefer-ip-address: true
    #status-page-url: http://192.168.88.189:8001/info

#配置DeptProvider8001 info信息 动态获取artifactId和version 用 ${}
info:
  app.name: taosun-microservicecloud
  company.name: 江苏曜晨科技有限公司
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}